version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"      # HTTP web UI and API
      - "8920:8920"      # Optional HTTPS
      - "7359:7359/udp"  # Service discovery
      - "1900:1900/udp"  # DLNA
    volumes:
      - /opt/homeserver/jellyfin/config:/config
      - /opt/homeserver/jellyfin/cache:/cache
      - /opt/homeserver/media:/media
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    user: nobody:nogroup
    volumes:
      - /opt/homeserver/prometheus/config:/etc/prometheus
      - /opt/homeserver/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    user: "472:472"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-logs:/var/log/grafana
      - grafana-plugins:/var/lib/grafana/plugins
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  grafana-data:
  grafana-logs:
  grafana-plugins: